apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:b0c4a5147a688c880e25b1217acab9d2e45bd33a
        ports:
        - containerPort: 80
