apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:cf06d880406f11f1d29e7a8fe3e859fb3748e4f1
        ports:
        - containerPort: 80
