apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:5fd3df087165fd6e3644da3a4264dfbe52650896
        ports:
        - containerPort: 80
