apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:c58dd8e43227df24ce4df264ca5ed8114749b6e7
        ports:
        - containerPort: 80
