apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:b0c4a5147a688c880e25b1217acab9d2e45bd33a
        ports:
        - containerPort: 80
