apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:cf06d880406f11f1d29e7a8fe3e859fb3748e4f1
        ports:
        - containerPort: 80
