apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-backend:367da09c6bdd70362c820febd58f2c7b5921f5ec
          ports:
            - containerPort: 5000
