apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-electronics:f17cb8c562f245127af20eda1e59e1c5f942ebba
        ports:
        - containerPort: 80
