apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-electronics:5fd3df087165fd6e3644da3a4264dfbe52650896
        ports:
        - containerPort: 80
