apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-main:5fd3df087165fd6e3644da3a4264dfbe52650896
        ports:
        - containerPort: 80

