apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlemusic:f17cb8c562f245127af20eda1e59e1c5f942ebba
        ports:
        - containerPort: 80
