apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-computers:c58dd8e43227df24ce4df264ca5ed8114749b6e7
        ports:
        - containerPort: 80
