apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-computers:c231a6ee3fd889c993b7542bc6bc8ac8317e544c
        ports:
        - containerPort: 80
