apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlepay:c58dd8e43227df24ce4df264ca5ed8114749b6e7
        ports:
        - containerPort: 80
