apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlepay:5fd3df087165fd6e3644da3a4264dfbe52650896
        ports:
        - containerPort: 80
