apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:bf9c14d6c42744f298cc412af738173cd956f804
        ports:
        - containerPort: 80
