apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:c58dd8e43227df24ce4df264ca5ed8114749b6e7
        ports:
        - containerPort: 80
