apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 357768534188.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:4aa0061bcb5434e1823ccb009f91fa321631679e
        ports:
        - containerPort: 80
