apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 905418310012.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:5f6b1613b4285406757989d95f5abd940e357105
        ports:
        - containerPort: 80
